name: glofrim3

channels:
  - defaults
  - conda-forge
  - http://pcraster.geo.uu.nl/pcraster/pcraster/

dependencies:
  - python>=3.7
  - numpy>=1.16.5
  - netcdf4>=1.4.2
  - rasterio>=1.1
  - rtree>=0.9.3
  - click>=7.0
  - configparser
  - python-dateutil>=2.8
  - pytz>=2019.3
  # - faulthandler #leads to conflicts
  - six>=1.14
  - pip>=20.0
  - pcraster>=4.3
  - pip:
    - bmi-python==0.2.6
    - git+https://github.com/openearth/glofrim.git@migrate_to_python3
